import React, { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

type SupportedLanguage = 'en' | 'es' | 'ar';

type TranslationMap = Record<string, string>;

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const en: TranslationMap = {
  'settings.title': 'Settings',
  'settings.description': 'Manage your app preferences and account settings',
  'settings.language': 'Language',
  'settings.language.description': 'Choose your preferred language',
  'language.english': 'English',
  'language.spanish': 'Spanish',
  'language.arabic': 'Arabic',
  'language.changed': 'Language changed to',
  'settings.notifications': 'Notifications',
  'settings.notifications.description': 'Get notified before scheduled workouts',
  'settings.notifications.progress.description': 'Weekly progress reports and achievements',
  'settings.notifications.meal.description': 'Reminders for meals and hydration',
  'settings.notifications.social.description': 'Messages from trainers and community',
  'settings.privacy': 'Privacy & Security',
  'settings.privacy.description': 'Control who can see your profile',
  'settings.privacy.data.description': 'Control how your data is shared',
  'settings.privacy.2fa.description': 'Add extra security to your account',
  'settings.privacy.password.description': 'Update your account password',
  'settings.preferences': 'App Preferences',
  'settings.preferences.description': 'Switch to dark theme',
  'settings.preferences.units': 'Units',
  'settings.preferences.units.description': 'Weight and distance units',
  'settings.account': 'Account Management',
  'settings.account.description': 'Export your data',
  'settings.account.support.description': 'Get help from our support team',
  'settings.account.delete.description': 'Delete your account and all data permanently',
  'workout.reminders': 'Workout Reminders',
  'progress.updates': 'Progress Updates',
  'meal.reminders': 'Meal Reminders',
  'social.notifications': 'Social Notifications',
  'profile.visibility': 'Profile Visibility',
  'profile.visibility.title': 'Profile Visibility',
  'profile.visibility.description': 'Control who can see your profile information',
  'profile.visibility.level': 'Visibility Level',
  'profile.visibility.public': 'Public - Anyone can see your profile',
  'profile.visibility.connections': 'Connections Only - Only your connections can see your profile',
  'profile.visibility.private': 'Private - Only you can see your profile',
  'profile.visibility.updated': 'Profile visibility updated',
  'data.sharing': 'Data Sharing',
  'data.sharing.title': 'Data Sharing Preferences',
  'data.sharing.description': 'Control how your data is shared',
  'data.sharing.analytics': 'Analytics Data',
  'data.sharing.analytics.description': 'Share anonymous usage data to improve the app',
  'data.sharing.thirdparty': 'Third-Party Integration',
  'data.sharing.thirdparty.description': 'Share data with connected third-party services',
  'data.sharing.marketing': 'Marketing Communications',
  'data.sharing.marketing.description': 'Receive personalized offers and updates',
  'data.sharing.updated': 'Data sharing preferences updated',
  'two.factor.auth': 'Two-Factor Authentication',
  '2fa.enrollment.initiated': '2FA enrollment initiated. Please complete setup in your authenticator app.',
  'change.password': 'Change Password',
  'password.change.title': 'Change Password',
  'password.change.description': 'Update your account password',
  'password.change.current': 'Current Password',
  'password.change.new': 'New Password',
  'password.change.confirm': 'Confirm New Password',
  'password.mismatch': 'Passwords do not match',
  'dark.mode': 'Dark Mode',
  'export.data': 'Export Data',
  'contact.support': 'Contact Support',
  'delete.account': 'Delete Account',
  'delete.account.confirm': 'Delete Account',
  'account.delete.title': 'Delete Account',
  'account.delete.confirm': 'Are you sure you want to delete your account?',
  'account.deletion.initiated': 'Account deletion initiated',
  'account.deletion.description': 'Your account will be deleted within 30 days.',
  'account.deletion.error': 'Failed to delete account',
  'support.contact.title': 'Contact Support',
  'support.contact.description': 'Get help with your account or app issues',
  'support.contact.message': 'Message',
  'support.contact.placeholder': 'Describe your issue or question...',
  'support.message.required': 'Please enter a message',
  'support.request.sent': 'Support request sent',
  'support.request.description': 'We will respond to your inquiry within 24 hours.',
  'sign.out': 'Sign Out',
  'sign.out.description': 'Sign out of your account',
  'sign.out.success': 'Signed out successfully',
  'manage': 'Manage',
  'configure': 'Configure',
  'loading': 'Loading...',
  'enabled': 'enabled',
  'disabled': 'disabled',
  'disable': 'Disable',
  'enable': 'Enable',
  'update': 'Update',
  'export': 'Export',
  'contact': 'Contact',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'save.changes': 'Save Changes',
  'send.message': 'Send Message',
  'units.changed': 'Units changed to',
  'data.export.requested': 'Data export requested',
  'data.export.description': 'Your data will be emailed to you shortly.',
  'data.export.error': 'Failed to export data',
};

const es: TranslationMap = {
  'settings.title': 'Configuración',
  'settings.description': 'Administra las preferencias de la aplicación y la cuenta',
  'settings.language': 'Idioma',
  'settings.language.description': 'Elige tu idioma preferido',
  'language.english': 'Inglés',
  'language.spanish': 'Español',
  'language.arabic': 'Árabe',
  'language.changed': 'Idioma cambiado a',
  'settings.notifications': 'Notificaciones',
  'settings.notifications.description': 'Recibe avisos antes de entrenamientos programados',
  'settings.notifications.progress.description': 'Informes semanales de progreso y logros',
  'settings.notifications.meal.description': 'Recordatorios de comidas e hidratación',
  'settings.notifications.social.description': 'Mensajes de entrenadores y comunidad',
  'settings.privacy': 'Privacidad y seguridad',
  'settings.privacy.description': 'Controla quién puede ver tu perfil',
  'settings.privacy.data.description': 'Controla cómo se comparten tus datos',
  'settings.privacy.2fa.description': 'Agrega seguridad adicional a tu cuenta',
  'settings.privacy.password.description': 'Actualiza la contraseña de tu cuenta',
  'settings.preferences': 'Preferencias de la app',
  'settings.preferences.description': 'Cambia al tema oscuro',
  'settings.preferences.units': 'Unidades',
  'settings.preferences.units.description': 'Unidades de peso y distancia',
  'settings.account': 'Gestión de cuenta',
  'settings.account.description': 'Exporta tus datos',
  'settings.account.support.description': 'Obtén ayuda de nuestro equipo de soporte',
  'settings.account.delete.description': 'Elimina tu cuenta y todos los datos de forma permanente',
  'workout.reminders': 'Recordatorios de entrenamiento',
  'progress.updates': 'Actualizaciones de progreso',
  'meal.reminders': 'Recordatorios de comidas',
  'social.notifications': 'Notificaciones sociales',
  'profile.visibility': 'Visibilidad del perfil',
  'profile.visibility.title': 'Visibilidad del perfil',
  'profile.visibility.description': 'Controla quién puede ver la información de tu perfil',
  'profile.visibility.level': 'Nivel de visibilidad',
  'profile.visibility.public': 'Público - Cualquiera puede ver tu perfil',
  'profile.visibility.connections': 'Solo contactos - Solo tus contactos pueden ver tu perfil',
  'profile.visibility.private': 'Privado - Solo tú puedes ver tu perfil',
  'profile.visibility.updated': 'Visibilidad del perfil actualizada',
  'data.sharing': 'Compartir datos',
  'data.sharing.title': 'Preferencias de compartir datos',
  'data.sharing.description': 'Controla cómo se comparten tus datos',
  'data.sharing.analytics': 'Datos analíticos',
  'data.sharing.analytics.description': 'Comparte datos de uso anónimos para mejorar la app',
  'data.sharing.thirdparty': 'Integración con terceros',
  'data.sharing.thirdparty.description': 'Comparte datos con servicios de terceros conectados',
  'data.sharing.marketing': 'Comunicaciones de marketing',
  'data.sharing.marketing.description': 'Recibe ofertas y actualizaciones personalizadas',
  'data.sharing.updated': 'Preferencias de compartir datos actualizadas',
  'two.factor.auth': 'Autenticación de dos factores',
  '2fa.enrollment.initiated': 'Registro de 2FA iniciado. Completa la configuración en tu app autenticadora.',
  'change.password': 'Cambiar contraseña',
  'password.change.title': 'Cambiar contraseña',
  'password.change.description': 'Actualiza la contraseña de tu cuenta',
  'password.change.current': 'Contraseña actual',
  'password.change.new': 'Nueva contraseña',
  'password.change.confirm': 'Confirmar nueva contraseña',
  'password.mismatch': 'Las contraseñas no coinciden',
  'dark.mode': 'Modo oscuro',
  'export.data': 'Exportar datos',
  'contact.support': 'Contactar soporte',
  'delete.account': 'Eliminar cuenta',
  'delete.account.confirm': 'Eliminar cuenta',
  'account.delete.title': 'Eliminar cuenta',
  'account.delete.confirm': '¿Seguro que quieres eliminar tu cuenta?',
  'account.deletion.initiated': 'Eliminación de cuenta iniciada',
  'account.deletion.description': 'Tu cuenta será eliminada dentro de 30 días.',
  'account.deletion.error': 'Error al eliminar la cuenta',
  'support.contact.title': 'Contactar soporte',
  'support.contact.description': 'Obtén ayuda con tu cuenta o problemas de la app',
  'support.contact.message': 'Mensaje',
  'support.contact.placeholder': 'Describe tu problema o pregunta...',
  'support.message.required': 'Por favor, introduce un mensaje',
  'support.request.sent': 'Solicitud de soporte enviada',
  'support.request.description': 'Responderemos a tu consulta dentro de 24 horas.',
  'sign.out': 'Cerrar sesión',
  'sign.out.description': 'Cerrar sesión de tu cuenta',
  'sign.out.success': 'Sesión cerrada correctamente',
  'manage': 'Gestionar',
  'configure': 'Configurar',
  'loading': 'Cargando...',
  'enabled': 'activado',
  'disabled': 'desactivado',
  'disable': 'Desactivar',
  'enable': 'Activar',
  'update': 'Actualizar',
  'export': 'Exportar',
  'contact': 'Contactar',
  'delete': 'Eliminar',
  'cancel': 'Cancelar',
  'save.changes': 'Guardar cambios',
  'send.message': 'Enviar mensaje',
  'units.changed': 'Unidades cambiadas a',
  'data.export.requested': 'Exportación de datos solicitada',
  'data.export.description': 'Tus datos se enviarán a tu correo en breve.',
  'data.export.error': 'Error al exportar datos',
};

const ar: TranslationMap = {
  'settings.title': 'الإعدادات',
  'settings.description': 'إدارة تفضيلات التطبيق وإعدادات الحساب',
  'settings.language': 'اللغة',
  'settings.language.description': 'اختر لغتك المفضلة',
  'language.english': 'الإنجليزية',
  'language.spanish': 'الإسبانية',
  'language.arabic': 'العربية',
  'language.changed': 'تم تغيير اللغة إلى',
  'settings.notifications': 'الإشعارات',
  'settings.notifications.description': 'احصل على إشعارات قبل التمارين المجدولة',
  'settings.notifications.progress.description': 'تقارير أسبوعية عن التقدم والإنجازات',
  'settings.notifications.meal.description': 'تذكيرات للوجبات والترطيب',
  'settings.notifications.social.description': 'رسائل من المدربين والمجتمع',
  'settings.privacy': 'الخصوصية والأمان',
  'settings.privacy.description': 'تحكم في من يمكنه رؤية ملفك الشخصي',
  'settings.privacy.data.description': 'تحكم في كيفية مشاركة بياناتك',
  'settings.privacy.2fa.description': 'أضف أمانًا إضافيًا إلى حسابك',
  'settings.privacy.password.description': 'حدّث كلمة مرور حسابك',
  'settings.preferences': 'تفضيلات التطبيق',
  'settings.preferences.description': 'التبديل إلى الوضع الداكن',
  'settings.preferences.units': 'الوحدات',
  'settings.preferences.units.description': 'وحدات الوزن والمسافة',
  'settings.account': 'إدارة الحساب',
  'settings.account.description': 'قم بتصدير بياناتك',
  'settings.account.support.description': 'احصل على المساعدة من فريق الدعم',
  'settings.account.delete.description': 'احذف حسابك وجميع البيانات نهائيًا',
  'workout.reminders': 'تذكيرات التمرين',
  'progress.updates': 'تحديثات التقدم',
  'meal.reminders': 'تذكيرات الوجبات',
  'social.notifications': 'إشعارات اجتماعية',
  'profile.visibility': 'رؤية الملف الشخصي',
  'profile.visibility.title': 'رؤية الملف الشخصي',
  'profile.visibility.description': 'تحكم في من يمكنه رؤية معلومات ملفك الشخصي',
  'profile.visibility.level': 'مستوى الرؤية',
  'profile.visibility.public': 'عام - يمكن لأي شخص رؤية ملفك الشخصي',
  'profile.visibility.connections': 'جهات الاتصال فقط - فقط جهات اتصالك يمكنهم رؤية ملفك',
  'profile.visibility.private': 'خاص - أنت فقط من يمكنه رؤية ملفك',
  'profile.visibility.updated': 'تم تحديث رؤية الملف الشخصي',
  'data.sharing': 'مشاركة البيانات',
  'data.sharing.title': 'تفضيلات مشاركة البيانات',
  'data.sharing.description': 'تحكم في كيفية مشاركة بياناتك',
  'data.sharing.analytics': 'بيانات التحليلات',
  'data.sharing.analytics.description': 'شارك بيانات استخدام مجهولة لتحسين التطبيق',
  'data.sharing.thirdparty': 'تكامل الطرف الثالث',
  'data.sharing.thirdparty.description': 'شارك البيانات مع خدمات الطرف الثالث المتصلة',
  'data.sharing.marketing': 'اتصالات التسويق',
  'data.sharing.marketing.description': 'استلم عروضًا وتحديثات مخصصة',
  'data.sharing.updated': 'تم تحديث تفضيلات مشاركة البيانات',
  'two.factor.auth': 'المصادقة الثنائية',
  '2fa.enrollment.initiated': 'تم بدء تفعيل المصادقة الثنائية. أكمل الإعداد في تطبيق المصادقة.',
  'change.password': 'تغيير كلمة المرور',
  'password.change.title': 'تغيير كلمة المرور',
  'password.change.description': 'حدّث كلمة مرور حسابك',
  'password.change.current': 'كلمة المرور الحالية',
  'password.change.new': 'كلمة المرور الجديدة',
  'password.change.confirm': 'تأكيد كلمة المرور الجديدة',
  'password.mismatch': 'كلمتا المرور غير متطابقتين',
  'dark.mode': 'الوضع الداكن',
  'export.data': 'تصدير البيانات',
  'contact.support': 'الاتصال بالدعم',
  'delete.account': 'حذف الحساب',
  'delete.account.confirm': 'حذف الحساب',
  'account.delete.title': 'حذف الحساب',
  'account.delete.confirm': 'هل أنت متأكد أنك تريد حذف حسابك؟',
  'account.deletion.initiated': 'تم بدء حذف الحساب',
  'account.deletion.description': 'سيتم حذف حسابك خلال 30 يومًا.',
  'account.deletion.error': 'فشل حذف الحساب',
  'support.contact.title': 'الاتصال بالدعم',
  'support.contact.description': 'احصل على مساعدة بخصوص حسابك أو مشاكل التطبيق',
  'support.contact.message': 'الرسالة',
  'support.contact.placeholder': 'صف مشكلتك أو سؤالك...',
  'support.message.required': 'يرجى إدخال رسالة',
  'support.request.sent': 'تم إرسال طلب الدعم',
  'support.request.description': 'سنرد على استفسارك خلال 24 ساعة.',
  'sign.out': 'تسجيل الخروج',
  'sign.out.description': 'تسجيل الخروج من حسابك',
  'sign.out.success': 'تم تسجيل الخروج بنجاح',
  'manage': 'إدارة',
  'configure': 'إعداد',
  'loading': 'جارٍ التحميل...',
  'enabled': 'مفعّل',
  'disabled': 'معطّل',
  'disable': 'تعطيل',
  'enable': 'تفعيل',
  'update': 'تحديث',
  'export': 'تصدير',
  'contact': 'اتصال',
  'delete': 'حذف',
  'cancel': 'إلغاء',
  'save.changes': 'حفظ التغييرات',
  'send.message': 'إرسال الرسالة',
  'units.changed': 'تم تغيير الوحدات إلى',
  'data.export.requested': 'تم طلب تصدير البيانات',
  'data.export.description': 'سيتم إرسال بياناتك إلى بريدك الإلكتروني قريبًا.',
  'data.export.error': 'فشل تصدير البيانات',
};

const translations: Record<SupportedLanguage, TranslationMap> = { en, es, ar };

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage === 'en' || savedLanguage === 'es' || savedLanguage === 'ar') {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: (newLanguage: string) => {
        if (newLanguage === 'en' || newLanguage === 'es' || newLanguage === 'ar') {
          setLanguage(newLanguage);
        }
      },
      t,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
