name: The PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: Codium-ai/pr-agent@v0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
