name: Super-Linter

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          FILTER_REGEX_EXCLUDE: .*dist/.*
